apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-pod
  template:
    metadata:
      labels:
        app: catalog-pod
    spec:
      containers:
      - name: catalog-container
        image: sandeepsoni/eshop-catalog
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent
        env:
        - name: ConnectionStrings__ProductCatalogApiContext
          value: "Server=mssqlserver-srv;Database=CatalogDb;User Id=sa;Password=Password_123"
      restartPolicy: Always
---

apiVersion: v1
kind: Service
metadata:
  name: catalog-srv
spec:
  type: ClusterIP
  selector:
    app: catalog-pod
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: catalog-srv-lb
spec:
  type: LoadBalancer
  selector:
    app: catalog-pod
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 80
