apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-pod
  template:
    metadata:
      labels:
        app: catalog-pod
    spec:
      containers:
      - name: catalog-container
        image: acreshopcap.azurecr.io/productcatalogapi

        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent
        env:
        - name: Logging__LogLevel__Default
          value: "Information"
        - name: Logging__LogLevel__Microsoft.AspNetCore
          value: "Warning"
        - name: AppConfig__Endpoint
          value: "Endpoint=https://appconfig-eshop.azconfig.io;Id=RLQE;Secret=5OKT5v4hRmcXTcqjZwHa75bdiqBZwOFGGzczU87MiqQ="

      restartPolicy: Always
---

apiVersion: v1
kind: Service
metadata:
  name: catalog-svc
spec:
  type: ClusterIP
  selector:
    app: catalog-pod
  ports:
    - name: http
      protocol: TCP
      port: 80


