apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshopui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eshop-pod
  template:
    metadata:
      labels:
        app: eshop-pod
    spec:
      containers:
      - name: eshop-container
        image: acreshopcap.azurecr.io/eshopui
        ports:
        - containerPort: 80
        - containerPort: 443
        imagePullPolicy: IfNotPresent
        env:
        - name: CatalogUrl
          value: "http://catalog-svc"
        - name: ShoppingCartUrl
          value: "http://cart-svc"
        - name: NotificationUrl
          value: "http://notification-svc"
        - name: Logging__LogLevel__Default
          value: "Information"
        - name: Logging__LogLevel__Microsoft.AspNetCore
          value: "Warning"
        - name: AppConfig__Endpoint
          value: "Endpoint=https://appconfig-eshop.azconfig.io;Id=RLQE;Secret=5OKT5v4hRmcXTcqjZwHa75bdiqBZwOFGGzczU87MiqQ="

---

apiVersion: v1
kind: Service
metadata:
  name: eshop
spec:
  type: ClusterIP
  selector:
    app: eshop-pod
  ports:
    - name: http
      protocol: TCP
      port: 80
    - name: https
      port: 443
